const {chromium}=require('playwright');const fs=require('fs');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch();try{for(const width of [1440,390]){
const page=await browser.newPage({viewport:{width,height:900},bypassCSP:true});const batches=[];
await page.route('**/api/translate/user-content',async route=>{const {texts}=route.request().postDataJSON();batches.push(texts);assert(texts.length<=12);assert(texts.reduce((n,t)=>n+t.length,0)<=4500);assert(texts.every(t=>t.length<=500));await new Promise(r=>setTimeout(r,50));await route.fulfill({json:{translations:texts.map(()=> 'Translated content')}})});
await page.route('**/api/**',route=>route.request().url().includes('/api/translate/')?route.fallback():route.fulfill({json:{categories:[],user:null}}));
await page.route('https://example.test/',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><body></body>'}));await page.goto('https://example.test/');
let html=fs.readFileSync('dist/index.html','utf8').replace(/<script\b[\s\S]*?<\/script>/gi,'').replace(/<link\b[^>]*>/gi,'');await page.setContent(html);
await page.evaluate(()=>{document.documentElement.lang='en';document.documentElement.dir='ltr';localStorage.setItem('gmach-language','en')});
await page.addStyleTag({content:fs.readFileSync('dist/styles.css','utf8')});
for(const file of ['i18n-en.js','i18n-errors.js'])await page.addScriptTag({content:fs.readFileSync('dist/'+file,'utf8')});
const runtime=fs.readFileSync('dist/remaining-features.js','utf8');const prefix=runtime.slice(runtime.indexOf('const I18N='),runtime.indexOf('function installLanguage()'));const tail=runtime.slice(runtime.lastIndexOf('Object.assign(I18N.en,'),runtime.indexOf('function init()'));
await page.addScriptTag({content:'(()=>{const $$=(s,r=document)=>[...r.querySelectorAll(s)];'+prefix+'\n'+tail+'translate(document.body);observeTranslations();})()'});
// Every static label (including currently closed dialogs) must work without AI.
const missing=await page.evaluate(()=>{const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),out=[];let n;while(n=w.nextNode())if(/[\u0590-\u05ff]/.test(n.nodeValue)&&!n.parentElement.closest('script,style'))out.push(n.nodeValue.trim());return out});assert.deepEqual(missing,[]);
await page.addScriptTag({content:fs.readFileSync('dist/user-content-translation.js','utf8')});
await page.evaluate(()=>{const f=document.createElement('section');f.id='english-fixture';f.innerHTML='<h2 class="organization-name" translate="no">גמ״ח ציוד ירושלים</h2><p id="dynamic-ui">הקצאת יחידות</p><p id="long-description"></p><p data-no-translate id="content">תוכן חופשי חדש</p><p id="same-content">תוכן חופשי חדש</p><textarea placeholder="תיאור חופשי חדש"></textarea><img alt="תמונה חדשה"><select><option>אפשרות חדשה</option></select><script type="application/json" id="original-data">{"name":"נתון מקורי"}</script>';document.body.prepend(f);document.querySelector('#long-description').textContent='תיאור ארוך מאוד של ציוד ופרטים נוספים '.repeat(40)});
await page.waitForFunction(()=>document.querySelector('#long-description').textContent.includes('Translated content')&&!/[\u0590-\u05ff]/.test(document.querySelector('#long-description').textContent),null,{timeout:15000});
await page.waitForFunction(()=>!/[\u0590-\u05ff]/.test(document.querySelector('#english-fixture textarea').placeholder+document.querySelector('#english-fixture img').alt+document.querySelector('#content').textContent+document.querySelector('#english-fixture option').textContent));
assert.equal(await page.locator('#dynamic-ui').textContent(),'Allocate units');assert.equal(await page.locator('.organization-name').first().textContent(),'גמ״ח ציוד ירושלים');assert.equal(await page.locator('#original-data').textContent(),'{"name":"נתון מקורי"}');assert.equal(await page.locator('#english-fixture option').getAttribute('value'),'אפשרות חדשה');assert.equal(batches.flat().filter(s=>s==='תוכן חופשי חדש').length,1);
// A user change made while a translation is in flight must survive.
await page.evaluate(()=>{const el=document.createElement('p');el.id='race';el.textContent='טקסט ישן לתרגום';document.body.prepend(el)});await page.waitForRequest(r=>r.url().includes('/api/translate/')&&r.postData().includes('טקסט ישן'));await page.evaluate(()=>document.querySelector('#race').textContent='New user content');await page.waitForTimeout(200);assert.equal(await page.locator('#race').textContent(),'New user content');
await page.screenshot({path:'test/english-previews/'+width+'.png'});console.log(JSON.stringify({width,staticLabels:true,longContent:true,attributes:true,preservedNames:true,originalData:true,requestDeduplication:true,staleResponse:true,batches:batches.length}));await page.close();
}}finally{await browser.close()}})().catch(error=>{console.error(error);process.exit(1)});
