PRAGMA foreign_keys = ON;

ALTER TABLE email_templates ADD COLUMN design_json TEXT NOT NULL DEFAULT '{}';

INSERT OR IGNORE INTO email_templates(template_key,language,subject,body_text,enabled,design_json) VALUES
('verification','he','קוד האימות שלך לגמ״ח ברגע','שלום {{full_name}},\n\nקוד האימות שלך הוא {{code}}.\nהקוד תקף ל־10 דקות. אם לא ביקשת להירשם, אפשר להתעלם מהמייל.',1,'{"primaryColor":"#243f75","backgroundColor":"#f5f7f8","cardColor":"#ffffff","textColor":"#15313a","buttonColor":"#ad7b35","showLogo":true,"logoUrl":"https://gmach-berega.co.il/gmach-berega-logo.jpg","borderRadius":20,"footerText":"אין להשיב למייל זה."}'),
('verification','en','Your Gmach Berega verification code','Hello {{full_name}},\n\nYour verification code is {{code}}.\nIt expires in 10 minutes. If you did not sign up, you can ignore this email.',1,'{"primaryColor":"#243f75","backgroundColor":"#f5f7f8","cardColor":"#ffffff","textColor":"#15313a","buttonColor":"#ad7b35","showLogo":true,"logoUrl":"https://gmach-berega.co.il/gmach-berega-logo.jpg","borderRadius":20,"footerText":"Do not reply to this email."}'),
('password_reset','he','איפוס סיסמה בגמ״ח ברגע','שלום {{full_name}},\n\nקוד איפוס הסיסמה שלך הוא {{code}}.\nהקוד תקף ל־10 דקות. אם לא ביקשת זאת, אפשר להתעלם מהמייל.',1,'{"primaryColor":"#243f75","backgroundColor":"#f5f7f8","cardColor":"#ffffff","textColor":"#15313a","buttonColor":"#ad7b35","showLogo":true,"logoUrl":"https://gmach-berega.co.il/gmach-berega-logo.jpg","borderRadius":20,"footerText":"אין להשיב למייל זה."}'),
('password_reset','en','Reset your Gmach Berega password','Hello {{full_name}},\n\nYour password reset code is {{code}}.\nIt expires in 10 minutes. If you did not request this, you can ignore this email.',1,'{"primaryColor":"#243f75","backgroundColor":"#f5f7f8","cardColor":"#ffffff","textColor":"#15313a","buttonColor":"#ad7b35","showLogo":true,"logoUrl":"https://gmach-berega.co.il/gmach-berega-logo.jpg","borderRadius":20,"footerText":"Do not reply to this email."}'),
('manager_invite','he','הזמנה לניהול {{organization_name}}','הוזמנת להצטרף כמנהל/ת של {{organization_name}}.\nהקישור בתוקף לשבעה ימים.',1,'{"primaryColor":"#243f75","backgroundColor":"#f5f7f8","cardColor":"#ffffff","textColor":"#15313a","buttonColor":"#ad7b35","buttonText":"פתיחת ההזמנה","showLogo":true,"logoUrl":"https://gmach-berega.co.il/gmach-berega-logo.jpg","borderRadius":20,"footerText":"גמ״ח ברגע"}'),
('manager_invite','en','Invitation to manage {{organization_name}}','You were invited to manage {{organization_name}}.\nThis invitation expires in seven days.',1,'{"primaryColor":"#243f75","backgroundColor":"#f5f7f8","cardColor":"#ffffff","textColor":"#15313a","buttonColor":"#ad7b35","buttonText":"Open invitation","showLogo":true,"logoUrl":"https://gmach-berega.co.il/gmach-berega-logo.jpg","borderRadius":20,"footerText":"Gmach Berega"}');
