
INSERT OR IGNORE INTO email_templates(template_key,language,subject,body_text,enabled,design_json) VALUES
('verification','he','קוד האימות שלך לגמ״ח ברגע','שלום {{full_name}},\n\nקוד האימות שלך הוא {{code}}.\nהקוד תקף ל־10 דקות. אם לא ביקשת להירשם, אפשר להתעלם מהמייל.',1,'{"primaryColor":"#243f75","backgroundColor":"#f5f7f8","cardColor":"#ffffff","textColor":"#15313a","buttonColor":"#ad7b35","showLogo":true,"logoUrl":"https://gmach-berega.co.il/gmach-berega-logo.jpg","borderRadius":20,"footerText":"אין להשיב למייל זה."}'),
('verification','en','Your Gmach Berega verification code','Hello {{full_name}},\n\nYour verification code is {{code}}.\nIt expires in 10 minutes. If you did not sign up, you can ignore this email.',1,'{"primaryColor":"#243f75","backgroundColor":"#f5f7f8","cardColor":"#ffffff","textColor":"#15313a","buttonColor":"#ad7b35","showLogo":true,"logoUrl":"https://gmach-berega.co.il/gmach-berega-logo.jpg","borderRadius":20,"footerText":"Do not reply to this email."}'),
('password_reset','he','איפוס סיסמה בגמ״ח ברגע','שלום {{full_name}},\n\nקוד איפוס הסיסמה שלך הוא {{code}}.\nהקוד תקף ל־10 דקות. אם לא ביקשת זאת, אפשר להתעלם מהמייל.',1,'{"primaryColor":"#243f75","backgroundColor":"#f5f7f8","cardColor":"#ffffff","textColor":"#15313a","buttonColor":"#ad7b35","showLogo":true,"logoUrl":"https://gmach-berega.co.il/gmach-berega-logo.jpg","borderRadius":20,"footerText":"אין להשיב למייל זה."}'),
('password_reset','en','Reset your Gmach Berega password','Hello {{full_name}},\n\nYour password reset code is {{code}}.\nIt expires in 10 minutes. If you did not request this, you can ignore this email.',1,'{"primaryColor":"#243f75","backgroundColor":"#f5f7f8","cardColor":"#ffffff","textColor":"#15313a","buttonColor":"#ad7b35","showLogo":true,"logoUrl":"https://gmach-berega.co.il/gmach-berega-logo.jpg","borderRadius":20,"footerText":"Do not reply to this email."}'),
('manager_invite','he','הזמנה לניהול {{organization_name}}','הוזמנת להצטרף כמנהל/ת של {{organization_name}}.\nהקישור בתוקף לשבעה ימים.',0,'{"primaryColor":"#243f75","backgroundColor":"#f5f7f8","cardColor":"#ffffff","textColor":"#15313a","buttonColor":"#ad7b35","buttonText":"פתיחת ההזמנה","showLogo":true,"logoUrl":"https://gmach-berega.co.il/gmach-berega-logo.jpg","borderRadius":20,"footerText":"גמ״ח ברגע"}'),
('manager_invite','en','Invitation to manage {{organization_name}}','You were invited to manage {{organization_name}}.\nThis invitation expires in seven days.',0,'{"primaryColor":"#243f75","backgroundColor":"#f5f7f8","cardColor":"#ffffff","textColor":"#15313a","buttonColor":"#ad7b35","buttonText":"Open invitation","showLogo":true,"logoUrl":"https://gmach-berega.co.il/gmach-berega-logo.jpg","borderRadius":20,"footerText":"Gmach Berega"}'),
('notification','he','עדכון חדש בגמ״ח ברגע','{{title}}\n\n{{body}}\n\nלצפייה בפרטים: {{account_url}}',0,'{}'),
('notification','en','New Gmach Berega update','You have a new update in your account.\n\n{{title}}\n{{body}}\n\nOpen your account: {{account_url}}',0,'{}'),
('daily_digest','he','הסיכום היומי שלך מגמ״ח ברגע','{{body}}\n\nלצפייה באזור האישי: {{account_url}}',0,'{}'),
('daily_digest','en','Your daily Gmach Berega summary','{{body}}\n\nOpen your account: {{account_url}}',0,'{}');
-- Apply the administrator's temporary auth-only email choice once.
CREATE TABLE IF NOT EXISTS email_control_rollouts (rollout_key TEXT PRIMARY KEY, applied_at TEXT NOT NULL);
UPDATE email_templates SET enabled=CASE WHEN template_key IN ('verification','password_reset') THEN 1 ELSE 0 END,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE NOT EXISTS (SELECT 1 FROM email_control_rollouts WHERE rollout_key='auth-only-2026-10-04-v2');
INSERT OR IGNORE INTO email_control_rollouts(rollout_key,applied_at) VALUES('auth-only-2026-10-04-v2',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
